"""
Gera uma base XLSX simulada de vagas de emprego no Brasil.

Uso:
    python gerar_base_vagas.py

Saída:
    dados/vagas_simuladas.xlsx
"""

import os
import pandas as pd

os.makedirs("dados", exist_ok=True)

vagas = [
    {
        "id_vaga": 1,
        "empresa": "TechSul Sistemas",
        "cargo": "Desenvolvedor Python Júnior",
        "data_publicacao": "2026-06-01",
        "tecnologias": "Python, Pandas, APIs REST, Git",
        "desafios": "Automatizar rotinas internas e criar integrações simples com APIs.",
        "perfil_desejado": "Conhecimento básico em Python, lógica de programação e vontade de aprender.",
        "modalidade": "Remoto",
        "cidade": "Joinville",
        "estado": "SC",
        "senioridade": "Júnior",
        "area": "Desenvolvimento",
        "tipo_contrato": "CLT",
        "ingles": "Básico",
        "salario_estimado": "R$ 3.000 a R$ 4.200",
        "beneficios": "Vale alimentação, plano de saúde, auxílio educação",
        "requisitos_obrigatorios": "Python básico, Git, lógica de programação",
        "requisitos_desejaveis": "Conhecimento em Streamlit e automação de tarefas",
        "atividades": "Criar scripts, consumir APIs, gerar relatórios e apoiar automações internas.",
        "ferramentas": "VS Code, GitHub, Excel, Postman",
        "descricao": "Vaga para atuar no desenvolvimento de scripts Python e pequenas automações para áreas administrativas.",
    },
    {
        "id_vaga": 2,
        "empresa": "DataBridge Analytics",
        "cargo": "Analista de Dados Pleno",
        "data_publicacao": "2026-06-03",
        "tecnologias": "SQL, Python, Power BI, Excel",
        "desafios": "Construir dashboards e análises para apoiar decisões comerciais.",
        "perfil_desejado": "Pessoa analítica, com boa comunicação e experiência em dados.",
        "modalidade": "Híbrido",
        "cidade": "Curitiba",
        "estado": "PR",
        "senioridade": "Pleno",
        "area": "Dados",
        "tipo_contrato": "CLT",
        "ingles": "Intermediário",
        "salario_estimado": "R$ 6.000 a R$ 8.000",
        "beneficios": "VR, plano de saúde, bônus anual",
        "requisitos_obrigatorios": "SQL, Power BI, análise exploratória",
        "requisitos_desejaveis": "Python, storytelling com dados",
        "atividades": "Criar dashboards, modelar bases, analisar indicadores e apresentar resultados.",
        "ferramentas": "Power BI, SQL Server, Python, Excel",
        "descricao": "Vaga focada em análise de indicadores, criação de relatórios e apoio estratégico às áreas de negócio.",
    },
    {
        "id_vaga": 3,
        "empresa": "CloudMind AI",
        "cargo": "Engenheiro de IA",
        "data_publicacao": "2026-06-04",
        "tecnologias": "Python, OpenAI API, LangChain, FastAPI, Docker",
        "desafios": "Criar assistentes virtuais integrados a sistemas corporativos.",
        "perfil_desejado": "Experiência com APIs de IA, arquitetura de software e integrações.",
        "modalidade": "Remoto",
        "cidade": "São Paulo",
        "estado": "SP",
        "senioridade": "Sênior",
        "area": "Inteligência Artificial",
        "tipo_contrato": "PJ",
        "ingles": "Avançado",
        "salario_estimado": "R$ 14.000 a R$ 20.000",
        "beneficios": "Contrato remoto, horário flexível, bônus por projeto",
        "requisitos_obrigatorios": "Python, APIs de LLM, Docker, FastAPI",
        "requisitos_desejaveis": "Agentes de IA, RAG, cloud AWS ou GCP",
        "atividades": "Projetar agentes, integrar modelos de linguagem e criar aplicações inteligentes.",
        "ferramentas": "OpenAI, Docker, FastAPI, GitHub Actions",
        "descricao": "Vaga para construção de soluções com LLMs, chatbots corporativos e automações inteligentes.",
    },
    {
        "id_vaga": 4,
        "empresa": "LogiTrack Brasil",
        "cargo": "Analista de Automação RPA",
        "data_publicacao": "2026-06-05",
        "tecnologias": "Python, Selenium, PyAutoGUI, Pandas, Excel",
        "desafios": "Automatizar processos repetitivos em sistemas internos e páginas web.",
        "perfil_desejado": "Boa lógica, atenção a detalhes e interesse em automação.",
        "modalidade": "Presencial",
        "cidade": "Itajaí",
        "estado": "SC",
        "senioridade": "Júnior",
        "area": "Automação",
        "tipo_contrato": "CLT",
        "ingles": "Básico",
        "salario_estimado": "R$ 3.500 a R$ 4.800",
        "beneficios": "Vale transporte, refeição, plano odontológico",
        "requisitos_obrigatorios": "Python, Excel, noções de Selenium",
        "requisitos_desejaveis": "Power Automate, APIs REST",
        "atividades": "Criar robôs para coleta de dados, manipulação de arquivos e preenchimento de sistemas.",
        "ferramentas": "VS Code, Selenium, Excel, Navegador Chrome",
        "descricao": "Vaga voltada à automação de tarefas administrativas e operacionais com Python.",
    },
    {
        "id_vaga": 5,
        "empresa": "FinCore Digital",
        "cargo": "Desenvolvedor Backend",
        "data_publicacao": "2026-06-06",
        "tecnologias": "Node.js, TypeScript, PostgreSQL, APIs REST",
        "desafios": "Desenvolver serviços escaláveis para plataforma financeira.",
        "perfil_desejado": "Experiência com backend, banco de dados e boas práticas de API.",
        "modalidade": "Remoto",
        "cidade": "Florianópolis",
        "estado": "SC",
        "senioridade": "Pleno",
        "area": "Desenvolvimento",
        "tipo_contrato": "CLT",
        "ingles": "Intermediário",
        "salario_estimado": "R$ 8.000 a R$ 11.000",
        "beneficios": "VR, home office, auxílio equipamento",
        "requisitos_obrigatorios": "Node.js, TypeScript, PostgreSQL",
        "requisitos_desejaveis": "Docker, microsserviços, mensageria",
        "atividades": "Criar APIs, manter serviços backend e otimizar consultas SQL.",
        "ferramentas": "GitHub, Docker, PostgreSQL, Insomnia",
        "descricao": "Vaga para atuação em backend de plataforma financeira com foco em APIs e escalabilidade.",
    },
    {
        "id_vaga": 6,
        "empresa": "EducaTech Labs",
        "cargo": "Instrutor de Tecnologia",
        "data_publicacao": "2026-06-07",
        "tecnologias": "Python, Streamlit, SQL, Git",
        "desafios": "Ensinar programação e projetos práticos para turmas iniciantes.",
        "perfil_desejado": "Boa comunicação, didática e domínio de fundamentos de programação.",
        "modalidade": "Híbrido",
        "cidade": "Joinville",
        "estado": "SC",
        "senioridade": "Pleno",
        "area": "Educação",
        "tipo_contrato": "PJ",
        "ingles": "Básico",
        "salario_estimado": "R$ 5.000 a R$ 7.000",
        "beneficios": "Horário flexível, bônus por turma, auxílio capacitação",
        "requisitos_obrigatorios": "Python, lógica de programação, didática",
        "requisitos_desejaveis": "Streamlit, IA generativa, experiência docente",
        "atividades": "Preparar aulas, conduzir exercícios e orientar projetos de alunos.",
        "ferramentas": "VS Code, Google Colab, GitHub, Streamlit",
        "descricao": "Vaga para professor ou mentor de tecnologia com foco em aulas práticas de programação e IA.",
    },
    {
        "id_vaga": 7,
        "empresa": "HealthData Solutions",
        "cargo": "Cientista de Dados",
        "data_publicacao": "2026-06-08",
        "tecnologias": "Python, Scikit-learn, SQL, Machine Learning",
        "desafios": "Criar modelos preditivos para análise de demanda e comportamento de pacientes.",
        "perfil_desejado": "Perfil analítico com experiência em modelagem estatística e machine learning.",
        "modalidade": "Remoto",
        "cidade": "Campinas",
        "estado": "SP",
        "senioridade": "Pleno",
        "area": "Ciência de Dados",
        "tipo_contrato": "CLT",
        "ingles": "Intermediário",
        "salario_estimado": "R$ 9.000 a R$ 12.000",
        "beneficios": "Plano de saúde, VR, participação nos resultados",
        "requisitos_obrigatorios": "Python, machine learning, SQL",
        "requisitos_desejaveis": "MLOps, cloud, estatística avançada",
        "atividades": "Treinar modelos, analisar dados, validar métricas e comunicar resultados.",
        "ferramentas": "Jupyter, Scikit-learn, SQL, Git",
        "descricao": "Vaga para desenvolvimento de modelos preditivos aplicados ao setor de saúde.",
    },
    {
        "id_vaga": 8,
        "empresa": "RetailFlow",
        "cargo": "Analista de Business Intelligence",
        "data_publicacao": "2026-06-09",
        "tecnologias": "Looker Studio, SQL, BigQuery, Excel",
        "desafios": "Criar painéis para acompanhamento de vendas e performance regional.",
        "perfil_desejado": "Boa visão de negócio, organização e domínio de indicadores.",
        "modalidade": "Híbrido",
        "cidade": "São José",
        "estado": "SC",
        "senioridade": "Júnior",
        "area": "BI",
        "tipo_contrato": "CLT",
        "ingles": "Básico",
        "salario_estimado": "R$ 4.000 a R$ 5.500",
        "beneficios": "VR, plano de saúde, auxílio home office",
        "requisitos_obrigatorios": "SQL, dashboards, Excel",
        "requisitos_desejaveis": "BigQuery, Looker Studio, storytelling",
        "atividades": "Construir dashboards, acompanhar KPIs e apoiar análises comerciais.",
        "ferramentas": "Looker Studio, BigQuery, Sheets, Excel",
        "descricao": "Vaga para criação de dashboards comerciais e análise de indicadores de varejo.",
    },
    {
        "id_vaga": 9,
        "empresa": "SecureOps",
        "cargo": "Analista de Segurança da Informação",
        "data_publicacao": "2026-06-10",
        "tecnologias": "ISO 27001, GRC, LGPD, SOC 2",
        "desafios": "Apoiar controles de segurança, auditorias e gestão de riscos.",
        "perfil_desejado": "Organização, visão de risco e conhecimento em normas de segurança.",
        "modalidade": "Remoto",
        "cidade": "Curitiba",
        "estado": "PR",
        "senioridade": "Pleno",
        "area": "Segurança da Informação",
        "tipo_contrato": "CLT",
        "ingles": "Intermediário",
        "salario_estimado": "R$ 7.000 a R$ 10.000",
        "beneficios": "Plano de saúde, previdência privada, auxílio educação",
        "requisitos_obrigatorios": "ISO 27001, gestão de riscos, políticas de segurança",
        "requisitos_desejaveis": "SOC 2, LGPD, auditoria interna",
        "atividades": "Revisar políticas, acompanhar riscos, apoiar auditorias e evidências.",
        "ferramentas": "Excel, SoftExpert, Jira, ferramentas GRC",
        "descricao": "Vaga para atuação em governança, riscos e compliance de segurança da informação.",
    },
    {
        "id_vaga": 10,
        "empresa": "AgroVision AI",
        "cargo": "Desenvolvedor de Visão Computacional",
        "data_publicacao": "2026-06-11",
        "tecnologias": "Python, OpenCV, PyTorch, YOLO",
        "desafios": "Criar modelos para detecção de objetos em imagens agrícolas.",
        "perfil_desejado": "Conhecimento em visão computacional, machine learning e processamento de imagens.",
        "modalidade": "Remoto",
        "cidade": "Londrina",
        "estado": "PR",
        "senioridade": "Pleno",
        "area": "Inteligência Artificial",
        "tipo_contrato": "PJ",
        "ingles": "Intermediário",
        "salario_estimado": "R$ 10.000 a R$ 14.000",
        "beneficios": "Horário flexível, projeto remoto, bônus por entrega",
        "requisitos_obrigatorios": "Python, OpenCV, redes neurais",
        "requisitos_desejaveis": "YOLO, PyTorch, deploy de modelos",
        "atividades": "Treinar modelos, processar imagens, avaliar métricas e implementar soluções.",
        "ferramentas": "Python, OpenCV, PyTorch, Git, Docker",
        "descricao": "Vaga para desenvolvimento de soluções de visão computacional aplicadas ao agronegócio.",
    },
]

df = pd.DataFrame(vagas)
df.to_excel("dados/vagas_simuladas.xlsx", index=False)

print("Base criada com sucesso em: dados/vagas_simuladas.xlsx")
